name:                telegram-countdown
version:             0.1.0.0
github:              "FabianGeiselhart/telegram-title-countdown"
license:             PublicDomain
author:              "f4814n"
maintainer:          "me@f4814n.de"
copyright:           "2018 Fabian Geiselhart"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/telegram-title-countdown#readme>

dependencies:
- base >= 4.7 && < 5
- telegram-api
- http-client
- http-client-tls
- text
- time
- safe
- timers
- pooled-io
- suspend
- MissingH

library:
  source-dirs: src

executables:
  telegram-countdown-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - telegram-countdown

tests:
  telegram-countdown-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - telegram-countdown
